{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "cf9479a1-affd-481d-a6f0-bffda279f6b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  residence         edu_diff  stunting_rate  underweight_rate  wasting_rate  \\\n",
      "0     Rural  Father < Mother           19.3               6.0          10.7   \n",
      "1     Rural  Father = Mother           20.3               6.6          10.1   \n",
      "2     Rural  Father > Mother           21.6               5.0           8.2   \n",
      "3     Urban  Father < Mother           19.1               6.6          10.3   \n",
      "4     Urban  Father = Mother           18.2               6.9          12.3   \n",
      "5     Urban  Father > Mother           19.9               7.6          12.2   \n",
      "6     Rural            Total           20.5               6.1           9.6   \n",
      "7     Urban            Total           18.7               6.9          11.9   \n",
      "\n",
      "   any_undernutrition_rate  all_undernutrition_rate     n  \n",
      "0                     29.4                      0.9   879  \n",
      "1                     29.9                      0.9  3227  \n",
      "2                     29.4                      0.5  1542  \n",
      "3                     28.8                      0.9   740  \n",
      "4                     30.2                      0.8  2283  \n",
      "5                     31.7                      0.8   662  \n",
      "6                     29.7                      0.8  5648  \n",
      "7                     30.2                      0.8  3685  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/zf/_tj8vxc92t1_zk8zhz_d81fh0000gn/T/ipykernel_29848/586838872.py:40: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.\n",
      "  summary = df_filtered.groupby([\"residence\", \"edu_diff\"]).agg(\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load the uploaded Output.csv file\n",
    "df = pd.read_csv(\"Output.csv\")\n",
    "\n",
    "# Select only the necessary columns and remove invalid values\n",
    "df_filtered = df[\n",
    "    (df[\"HW1\"] <= 59) &\n",
    "    (df[\"HW70\"] < 9990) &\n",
    "    (df[\"HW71\"] < 9990) &\n",
    "    (df[\"HW72\"] < 9990)\n",
    "].copy()\n",
    "\n",
    "# Create malnutrition indicators\n",
    "df_filtered[\"stunted\"] = (df_filtered[\"HW70\"] < -200).astype(int)\n",
    "df_filtered[\"underweight\"] = (df_filtered[\"HW71\"] < -200).astype(int)\n",
    "df_filtered[\"wasting\"] = (df_filtered[\"HW72\"] < -200).astype(int)\n",
    "df_filtered[\"any_undernutrition\"] = (\n",
    "    (df_filtered[\"stunted\"] == 1) |\n",
    "    (df_filtered[\"underweight\"] == 1) |\n",
    "    (df_filtered[\"wasting\"] == 1)\n",
    ").astype(int)\n",
    "df_filtered[\"all_undernutrition\"] = (\n",
    "    (df_filtered[\"stunted\"] == 1) &\n",
    "    (df_filtered[\"underweight\"] == 1) &\n",
    "    (df_filtered[\"wasting\"] == 1)\n",
    ").astype(int)\n",
    "\n",
    "# Create parental education comparison\n",
    "df_filtered[\"edu_diff\"] = pd.cut(\n",
    "    df_filtered[\"V701\"] - df_filtered[\"V106\"],\n",
    "    bins=[-float(\"inf\"), -1, 0, float(\"inf\")],\n",
    "    labels=[\"Father < Mother\", \"Father = Mother\", \"Father > Mother\"]\n",
    ")\n",
    "\n",
    "# Add residence label\n",
    "df_filtered[\"residence\"] = df_filtered[\"V025\"].map({1: \"Urban\", 2: \"Rural\"})\n",
    "\n",
    "# Group and summarize\n",
    "summary = df_filtered.groupby([\"residence\", \"edu_diff\"]).agg(\n",
    "    stunting_rate=(\"stunted\", lambda x: round(x.mean() * 100, 1)),\n",
    "    underweight_rate=(\"underweight\", lambda x: round(x.mean() * 100, 1)),\n",
    "    wasting_rate=(\"wasting\", lambda x: round(x.mean() * 100, 1)),\n",
    "    any_undernutrition_rate=(\"any_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    all_undernutrition_rate=(\"all_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    n=(\"stunted\", \"count\")\n",
    ").reset_index()\n",
    "\n",
    "# Add totals for each residence group\n",
    "totals = df_filtered.groupby(\"residence\").agg(\n",
    "    stunting_rate=(\"stunted\", lambda x: round(x.mean() * 100, 1)),\n",
    "    underweight_rate=(\"underweight\", lambda x: round(x.mean() * 100, 1)),\n",
    "    wasting_rate=(\"wasting\", lambda x: round(x.mean() * 100, 1)),\n",
    "    any_undernutrition_rate=(\"any_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    all_undernutrition_rate=(\"all_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    n=(\"stunted\", \"count\")\n",
    ").reset_index()\n",
    "\n",
    "totals[\"edu_diff\"] = \"Total\"\n",
    "final_summary = pd.concat([summary, totals], ignore_index=True)\n",
    "# To view the table\n",
    "print(final_summary)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d1a5d9de-3df2-4a6e-9b2f-7c19952944e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  residence   Father_occupation Mother_working_status  Stunted  Underweight  \\\n",
      "0     Rural    Service/Business           Not working     18.3          5.2   \n",
      "1     Rural    Service/Business               Working     18.2          9.1   \n",
      "2     Rural  Agriculture/Others           Not working     21.4          6.5   \n",
      "3     Rural  Agriculture/Others               Working     26.3          5.3   \n",
      "4     Urban    Service/Business           Not working     18.0          7.2   \n",
      "5     Urban    Service/Business               Working     12.5         12.5   \n",
      "6     Urban  Agriculture/Others           Not working     19.7          7.4   \n",
      "7     Urban  Agriculture/Others               Working     15.4          7.7   \n",
      "\n",
      "   Wasting  Any_undernutrition  All_undernutrition     N  \n",
      "0      8.6                26.7                 0.6  1716  \n",
      "1     18.2                36.4                 0.0    11  \n",
      "2     10.6                31.4                 0.9  3213  \n",
      "3      5.3                31.6                 0.0    19  \n",
      "4     12.2                29.9                 0.8  1594  \n",
      "5      0.0                25.0                 0.0     8  \n",
      "6     11.9                31.1                 0.9  1518  \n",
      "7      7.7                23.1                 0.0    13  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/zf/_tj8vxc92t1_zk8zhz_d81fh0000gn/T/ipykernel_26885/1495626722.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.\n",
      "  summary = df_filtered.groupby([\"residence\", \"Father_occupation\", \"Mother_working_status\"]).agg(\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Recode father's occupation\n",
    "df_filtered[\"Father_occupation\"] = pd.cut(\n",
    "    df_filtered[\"V704\"],\n",
    "    bins=[0, 54, 96],\n",
    "    labels=[\"Service/Business\", \"Agriculture/Others\"]\n",
    ")\n",
    "\n",
    "# Recode mother's working status\n",
    "df_filtered[\"Mother_working_status\"] = df_filtered[\"V731\"].map({1: \"Working\", 0: \"Not working\"})\n",
    "\n",
    "# Recode residence\n",
    "df_filtered[\"residence\"] = df_filtered[\"V025\"].map({1: \"Urban\", 2: \"Rural\"})\n",
    "\n",
    "# Group and calculate percentages\n",
    "summary = df_filtered.groupby([\"residence\", \"Father_occupation\", \"Mother_working_status\"]).agg(\n",
    "    Stunted=(\"stunted\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Underweight=(\"underweight\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Wasting=(\"wasting\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Any_undernutrition=(\"any_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    All_undernutrition=(\"all_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    N=(\"stunted\", \"count\")\n",
    ").reset_index()\n",
    "\n",
    "print(summary)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "16c3f959-ed85-4e54-a732-eacd83d626ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   residence   Maternal_education Mother_working_status  Stunted  Underweight  \\\n",
      "0      Rural         No education           Not working     24.2          6.8   \n",
      "1      Rural         No education               Working     28.2          8.3   \n",
      "2      Rural              Primary           Not working     24.1          8.6   \n",
      "3      Rural              Primary               Working     34.5          3.6   \n",
      "4      Rural  Secondary and above           Not working     18.0          5.3   \n",
      "5      Rural  Secondary and above               Working     17.6          5.6   \n",
      "6      Urban         No education           Not working     21.3          7.9   \n",
      "7      Urban         No education               Working     32.3          3.2   \n",
      "8      Urban              Primary           Not working     21.3          8.9   \n",
      "9      Urban              Primary               Working     18.2          0.0   \n",
      "10     Urban  Secondary and above           Not working     18.1          7.1   \n",
      "11     Urban  Secondary and above               Working     17.2          5.0   \n",
      "\n",
      "    Wasting  Any_Undernutrition  All_Undernutrition     N  \n",
      "0       9.9                33.4                 1.0  1362  \n",
      "1       8.3                35.9                 1.3   156  \n",
      "2       8.6                32.5                 1.1   535  \n",
      "3       1.8                36.4                 0.0    55  \n",
      "4      10.1                27.7                 0.7  3062  \n",
      "5       8.6                25.5                 0.6   478  \n",
      "6      11.2                33.1                 0.3   366  \n",
      "7      19.4                48.4                 3.2    31  \n",
      "8      12.8                33.3                 0.7   282  \n",
      "9       9.1                27.3                 0.0    22  \n",
      "10     12.0                29.7                 0.9  2485  \n",
      "11     10.8                27.9                 0.6   499  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/zf/_tj8vxc92t1_zk8zhz_d81fh0000gn/T/ipykernel_26885/1384704042.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.\n",
      "  summary_table = df_filtered.groupby([\"residence\", \"Maternal_education\", \"Mother_working_status\"]).agg(\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Recode maternal education\n",
    "df_filtered[\"Maternal_education\"] = pd.cut(\n",
    "    df_filtered[\"V106\"],\n",
    "    bins=[-1, 0, 1, 3],\n",
    "    labels=[\"No education\", \"Primary\", \"Secondary and above\"]\n",
    ")\n",
    "\n",
    "# Recode mother's working status (V714)\n",
    "df_filtered[\"Mother_working_status\"] = df_filtered[\"V714\"].map({1: \"Working\", 0: \"Not working\"})\n",
    "\n",
    "# Recode residence\n",
    "df_filtered[\"residence\"] = df_filtered[\"V025\"].map({1: \"Urban\", 2: \"Rural\"})\n",
    "\n",
    "# Group and summarize the results\n",
    "summary_table = df_filtered.groupby([\"residence\", \"Maternal_education\", \"Mother_working_status\"]).agg(\n",
    "    Stunted=(\"stunted\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Underweight=(\"underweight\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Wasting=(\"wasting\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Any_Undernutrition=(\"any_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    All_Undernutrition=(\"all_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    N=(\"stunted\", \"count\")\n",
    ").reset_index()\n",
    "\n",
    "print(summary_table)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "03f8cee9-43db-4289-b100-2cc445b856e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   residence     Father_education   Father_occupation  Stunted  Underweight  \\\n",
      "0      Rural         No education    Service/Business     23.6         12.6   \n",
      "1      Rural         No education  Agriculture/Others     25.3          7.1   \n",
      "2      Rural              Primary    Service/Business     24.3          7.2   \n",
      "3      Rural              Primary  Agriculture/Others     22.3          7.4   \n",
      "4      Rural  Secondary and above    Service/Business     17.7          4.8   \n",
      "5      Rural  Secondary and above  Agriculture/Others     19.9          5.8   \n",
      "6      Urban         No education    Service/Business     20.6          8.8   \n",
      "7      Urban         No education  Agriculture/Others     19.8          6.3   \n",
      "8      Urban              Primary    Service/Business     14.1          7.8   \n",
      "9      Urban              Primary  Agriculture/Others     23.0          8.7   \n",
      "10     Urban  Secondary and above    Service/Business     17.8          6.5   \n",
      "11     Urban  Secondary and above  Agriculture/Others     18.9          7.0   \n",
      "\n",
      "    Wasting  Any_Undernutrition  All_Undernutrition     N  \n",
      "0      14.2                34.6                 3.9   127  \n",
      "1       9.8                34.8                 0.9   814  \n",
      "2       9.9                33.6                 0.7   152  \n",
      "3      10.4                31.5                 1.4   701  \n",
      "4       8.2                25.8                 0.5  1808  \n",
      "5      10.3                29.9                 0.6  2046  \n",
      "6      14.7                37.3                 0.0   102  \n",
      "7      15.4                34.0                 1.6   253  \n",
      "8      10.9                25.8                 0.0   128  \n",
      "9      10.5                32.7                 1.2   343  \n",
      "10     11.7                29.1                 0.8  1774  \n",
      "11     11.6                30.2                 0.6  1085  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/zf/_tj8vxc92t1_zk8zhz_d81fh0000gn/T/ipykernel_26885/2161347629.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.\n",
      "  summary_table = df_filtered.groupby([\"residence\", \"Father_education\", \"Father_occupation\"]).agg(\n"
     ]
    }
   ],
   "source": [
    "# Recode father's education\n",
    "df_filtered[\"Father_education\"] = pd.cut(\n",
    "    df_filtered[\"V701\"],\n",
    "    bins=[-1, 0, 1, 3],\n",
    "    labels=[\"No education\", \"Primary\", \"Secondary and above\"]\n",
    ")\n",
    "\n",
    "# Recode father's occupation\n",
    "df_filtered[\"Father_occupation\"] = pd.cut(\n",
    "    df_filtered[\"V704\"],\n",
    "    bins=[0, 54, 96],\n",
    "    labels=[\"Service/Business\", \"Agriculture/Others\"]\n",
    ")\n",
    "\n",
    "# Recode residence\n",
    "df_filtered[\"residence\"] = df_filtered[\"V025\"].map({1: \"Urban\", 2: \"Rural\"})\n",
    "\n",
    "# Group and summarize the data\n",
    "summary_table = df_filtered.groupby([\"residence\", \"Father_education\", \"Father_occupation\"]).agg(\n",
    "    Stunted=(\"stunted\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Underweight=(\"underweight\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Wasting=(\"wasting\", lambda x: round(x.mean() * 100, 1)),\n",
    "    Any_Undernutrition=(\"any_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    All_Undernutrition=(\"all_undernutrition\", lambda x: round(x.mean() * 100, 1)),\n",
    "    N=(\"stunted\", \"count\")\n",
    ").reset_index()\n",
    "\n",
    "print(summary_table)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2b262d18-d886-4807-a8ff-521df4448f7d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "               Outcome                 Variable  M1_Urban  M1_Rural  M2_Urban  \\\n",
      "0   any_undernutrition       Mother's education    -0.039    -0.079    -0.029   \n",
      "1   any_undernutrition       Father's education    -0.028    -0.079    -0.002   \n",
      "2   any_undernutrition      Father's occupation     0.001     0.002     0.001   \n",
      "3   any_undernutrition  Mother's working status    -0.041    -0.031    -0.018   \n",
      "4              stunted       Mother's education    -0.031    -0.108    -0.019   \n",
      "5              stunted       Father's education    -0.026    -0.086    -0.004   \n",
      "6              stunted      Father's occupation     0.001     0.003     0.001   \n",
      "7              stunted  Mother's working status    -0.026     0.034    -0.005   \n",
      "8          underweight       Mother's education    -0.040    -0.056    -0.013   \n",
      "9          underweight       Father's education    -0.027    -0.098     0.011   \n",
      "10         underweight      Father's occupation     0.002     0.001     0.002   \n",
      "11         underweight  Mother's working status    -0.223     0.002    -0.204   \n",
      "12             wasting       Mother's education    -0.020     0.017    -0.016   \n",
      "13             wasting       Father's education    -0.011    -0.027     0.000   \n",
      "14             wasting      Father's occupation     0.000     0.000     0.000   \n",
      "15             wasting  Mother's working status    -0.039    -0.118    -0.030   \n",
      "\n",
      "    M2_Rural  M3_Urban  M3_Rural  \n",
      "0     -0.054    -0.033    -0.059  \n",
      "1     -0.039    -0.004    -0.041  \n",
      "2      0.001     0.000     0.001  \n",
      "3      0.008     0.010     0.029  \n",
      "4     -0.091    -0.019    -0.072  \n",
      "5     -0.026    -0.006    -0.022  \n",
      "6      0.001     0.001     0.001  \n",
      "7      0.083     0.013     0.106  \n",
      "8     -0.014    -0.011    -0.000  \n",
      "9     -0.096     0.011    -0.092  \n",
      "10    -0.001     0.002    -0.001  \n",
      "11     0.024    -0.193     0.038  \n",
      "12     0.045    -0.020    -0.004  \n",
      "13    -0.048    -0.000    -0.059  \n",
      "14     0.000    -0.000    -0.000  \n",
      "15    -0.121    -0.005    -0.123  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import statsmodels.api as sm\n",
    "from statsmodels.discrete.discrete_model import Probit\n",
    "\n",
    "\n",
    "# Filter and create outcome indicators\n",
    "probit_data = df[\n",
    "    (df[\"HW1\"] <= 59) &\n",
    "    (df[\"HW70\"] < 9990) & (df[\"HW71\"] < 9990) & (df[\"HW72\"] < 9990) &\n",
    "    (df[\"V106\"].between(0, 3)) & (df[\"V701\"].between(0, 3)) &\n",
    "    (df[\"V714\"].isin([0, 1])) & (df[\"V704\"].between(1, 96)) &\n",
    "    (df[\"V025\"].isin([1, 2]))\n",
    "].copy()\n",
    "\n",
    "# Recode residence\n",
    "probit_data[\"residence\"] = probit_data[\"V025\"].map({1: \"Urban\", 2: \"Rural\"})\n",
    "\n",
    "# Outcome indicators\n",
    "probit_data[\"stunted\"] = (probit_data[\"HW70\"] < -200).astype(int)\n",
    "probit_data[\"underweight\"] = (probit_data[\"HW71\"] < -200).astype(int)\n",
    "probit_data[\"wasting\"] = (probit_data[\"HW72\"] < -200).astype(int)\n",
    "probit_data[\"any_undernutrition\"] = (\n",
    "    probit_data[\"stunted\"] | probit_data[\"underweight\"] | probit_data[\"wasting\"]\n",
    ").astype(int)\n",
    "\n",
    "# Add recoded media access\n",
    "probit_data[\"media_access\"] = (\n",
    "    ((probit_data[\"V157\"].between(1, 3)) |\n",
    "     (probit_data[\"V158\"].between(1, 3)) |\n",
    "     (probit_data[\"V159\"].between(1, 3)))\n",
    ").astype(int)\n",
    "\n",
    "# Add BMI placeholder\n",
    "probit_data[\"BMI\"] = probit_data.get(\"Mother_BMI\", pd.NA)\n",
    "\n",
    "# Define variables\n",
    "outcomes = [\"stunted\", \"underweight\", \"wasting\", \"any_undernutrition\"]\n",
    "parental_vars = [\"V106\", \"V701\", \"V714\", \"V704\"]\n",
    "control_vars = [\"media_access\", \"V012\", \"V101\", \"V190\", \"V511\", \"V212\", \"HW1\", \"BORD\", \"V218\", \"B11\"]\n",
    "\n",
    "# Run models and store results\n",
    "all_results = []\n",
    "for outcome in outcomes:\n",
    "    for model in [\"Model 1\", \"Model 2\", \"Model 3\"]:\n",
    "        for res in [\"Urban\", \"Rural\"]:\n",
    "            df_sub = probit_data[probit_data[\"residence\"] == res].copy()\n",
    "            y = df_sub[outcome]\n",
    "\n",
    "            # Choose predictors based on model\n",
    "            if model == \"Model 1\":\n",
    "                for var in parental_vars:\n",
    "                    X = sm.add_constant(df_sub[[var]])\n",
    "                    try:\n",
    "                        probit = Probit(y, X).fit(disp=False)\n",
    "                        coef = round(probit.params[var], 3)\n",
    "                    except:\n",
    "                        coef = None\n",
    "                    all_results.append([outcome, var, model, res, coef])\n",
    "            elif model == \"Model 2\":\n",
    "                X = sm.add_constant(df_sub[parental_vars])\n",
    "                try:\n",
    "                    probit = Probit(y, X).fit(disp=False)\n",
    "                    for var in parental_vars:\n",
    "                        coef = round(probit.params[var], 3)\n",
    "                        all_results.append([outcome, var, model, res, coef])\n",
    "                except:\n",
    "                    for var in parental_vars:\n",
    "                        all_results.append([outcome, var, model, res, None])\n",
    "            elif model == \"Model 3\":\n",
    "                model3_vars = parental_vars + control_vars\n",
    "                available = [v for v in model3_vars if v in df_sub.columns and df_sub[v].notna().sum() > 0]\n",
    "                X = sm.add_constant(df_sub[available])\n",
    "                try:\n",
    "                    probit = Probit(y, X).fit(disp=False)\n",
    "                    for var in parental_vars:\n",
    "                        if var in probit.params:\n",
    "                            coef = round(probit.params[var], 3)\n",
    "                        else:\n",
    "                            coef = None\n",
    "                        all_results.append([outcome, var, model, res, coef])\n",
    "                except:\n",
    "                    for var in parental_vars:\n",
    "                        all_results.append([outcome, var, model, res, None])\n",
    "\n",
    "# Convert results to DataFrame\n",
    "flat_results_df = pd.DataFrame(all_results, columns=[\"Outcome\", \"Variable\", \"Model\", \"Residence\", \"Coefficient\"])\n",
    "\n",
    "# Pivot into table format like Table 7\n",
    "final_table = flat_results_df.pivot_table(\n",
    "    index=[\"Outcome\", \"Variable\"],\n",
    "    columns=[\"Model\", \"Residence\"],\n",
    "    values=\"Coefficient\",\n",
    "    aggfunc=\"first\"\n",
    ")[[\n",
    "    (\"Model 1\", \"Urban\"), (\"Model 1\", \"Rural\"),\n",
    "    (\"Model 2\", \"Urban\"), (\"Model 2\", \"Rural\"),\n",
    "    (\"Model 3\", \"Urban\"), (\"Model 3\", \"Rural\")\n",
    "]]\n",
    "\n",
    "# Rename columns\n",
    "final_table.columns = ['M1_Urban', 'M1_Rural', 'M2_Urban', 'M2_Rural', 'M3_Urban', 'M3_Rural']\n",
    "final_table = final_table.reset_index()\n",
    "\n",
    "# Optional: rename variables for display\n",
    "variable_labels = {\n",
    "    \"V106\": \"Mother's education\",\n",
    "    \"V701\": \"Father's education\",\n",
    "    \"V714\": \"Mother's working status\",\n",
    "    \"V704\": \"Father's occupation\"\n",
    "}\n",
    "final_table[\"Variable\"] = final_table[\"Variable\"].map(variable_labels)\n",
    "\n",
    "# Display or export\n",
    "print(final_table)\n",
    "# final_table.to_csv(\"probit_results_table7_style.csv\", index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38a8d141-2a98-4b47-97b6-2b0edbfa093d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
